use_frameworks!

platform :ios, '13.0'

target 'CommonSwift_Example' do
  pod 'CommonSwift', :path => '../'
  pod 'BigInt', '~> 3.1'

  target 'CommonSwift_Tests' do
    inherit! :search_paths

    
  end
end
